import type { APIRoute } from 'astro'
import type { HibpBreach } from '../lib/types'
import { getAllBreaches } from '../lib/hibp'
import { isIndexableCase } from '../lib/index-policy'
import {
  ARCHIVE_PAGE_SIZE,
  archiveCases,
  archivePageCount,
  archivePagePath,
} from '../lib/archive-index'
import { slugify } from '../lib/utils'

const siteUrl = 'https://traced.jonathanrreed.com'

/**
 * When each hand-written page last actually changed.
 *
 * These have to be literals. Cloudflare Pages builds from a shallow clone, so
 * there is no history to read here, and the build clock is worse: stamping
 * `new Date()` told crawlers every page changed on every deploy, which is the
 * quickest way to teach them that our lastmod means nothing. Case and archive
 * URLs don't need a table, they get their dates from the records they render.
 *
 * Only pages that are meant to rank are listed. /privacy/ renders noindex,follow.
 *
 * When you change what one of these pages says, change its date here too.
 */
const STATIC_PAGE_DATES: Record<string, string> = {
  '/': '2026-08-06',
  '/check/': '2026-08-04',
  '/about/': '2026-08-04',
  '/contact/': '2026-08-04',
}

/** Last edit to the /archive/ template itself. Its pages are at least this old. */
const ARCHIVE_TEMPLATE_DATE = '2026-08-06'

function escapeXml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;')
}

function toIsoDate(value: string | undefined): string | undefined {
  if (!value) return undefined
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return undefined
  return date.toISOString().slice(0, 10)
}

/** A case page is as old as the record it renders. */
function caseDate(breach: HibpBreach): string | undefined {
  return toIsoDate(breach.ModifiedDate) ?? toIsoDate(breach.AddedDate)
}

/**
 * An archive page is as fresh as the newest record it lists, floored at the
 * last edit to the template. Both inputs are content, so a rebuild that changes
 * nothing produces the same date, and a new breach landing in HIBP moves the
 * page it lands on without anyone editing this file.
 */
function archivePageDate(pageCases: HibpBreach[]): string {
  return pageCases.reduce((latest, breach) => {
    const date = caseDate(breach)
    return date && date > latest ? date : latest
  }, ARCHIVE_TEMPLATE_DATE)
}

function urlEntry(path: string, lastmod?: string): string {
  const loc = `    <loc>${escapeXml(new URL(path, siteUrl).toString())}</loc>`
  const lm = lastmod ? `\n    <lastmod>${lastmod}</lastmod>` : ''
  return `  <url>\n${loc}${lm}\n  </url>`
}

export const GET: APIRoute = async () => {
  const breaches = await getAllBreaches()
  const cases = archiveCases(breaches)

  // The /archive/ hub is generated by a paginated route, so its URLs are not in
  // `breaches` and have to be listed explicitly. Derived from the same helpers
  // the route uses, so the two can never disagree on how many pages exist, or
  // on which cases land on which page.
  const archivePages = Array.from(
    { length: archivePageCount(cases.length) },
    (_, i) => ({
      path: archivePagePath(i + 1),
      lastmod: archivePageDate(
        cases.slice(i * ARCHIVE_PAGE_SIZE, (i + 1) * ARCHIVE_PAGE_SIZE),
      ),
    }),
  )

  const entries = [
    ...Object.entries(STATIC_PAGE_DATES).map(([path, lastmod]) =>
      urlEntry(path, lastmod),
    ),
    ...archivePages.map(({ path, lastmod }) => urlEntry(path, lastmod)),
    // Must stay in step with caseRobots() in case/[name].astro: a submitted URL
    // that renders noindex is a wasted crawl.
    ...breaches
      .filter(isIndexableCase)
      .map((breach) => urlEntry(`/case/${slugify(breach.Name)}/`, caseDate(breach))),
  ]

  const body = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries.join(
    '\n',
  )}\n</urlset>\n`

  return new Response(body, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
    },
  })
}
